import { describe, it, expect } from "vitest";
import { createHash } from "node:crypto";
import { handler } from "../../../src/linter/programmatic/fugue-generated-integrity";

/** Build a stamped file exactly as fugue's codegen does: banner + integrity
 *  line (sha256 of the body) + body. Mirrors packages/framework's stampGenerated. */
function stamp(body: string): string {
  const hash = createHash("sha256").update(body, "utf8").digest("hex");
  return (
    "// @generated by `fugue new --from` — DO NOT EDIT; regenerate from dag.authored.json\n" +
    `// @fugue-integrity sha256:${hash}\n` +
    body
  );
}

const BODY = 'export const dag = defineDag({ nodes: [] });\n';

describe("fugue-generated-integrity", () => {
  it("passes when the body matches its stamped hash", () => {
    expect(handler(stamp(BODY), "dags/team/x/dag.ts")).toEqual([]);
  });

  it("flags a body that no longer matches the stamp (hand-edit)", () => {
    const tampered = stamp(BODY).replace("nodes: []", "nodes: [evil]");
    const violations = handler(tampered, "dags/team/x/dag.ts");
    expect(violations).toHaveLength(1);
    expect(violations[0].rule).toBe("fugue-generated-integrity");
    expect(violations[0].line).toBe(2); // points at the @fugue-integrity marker line
    expect(violations[0].fixHint).toContain("regenerate");
  });

  it("ignores files without the integrity marker (rule N/A)", () => {
    expect(handler("export const x = 1;\n", "src/hand-written.ts")).toEqual([]);
    expect(handler("// @generated but no integrity line\nexport const x = 1;\n", "x.ts")).toEqual([]);
  });

  it("rejects a corrupted/truncated hash marker as non-matching (not a silent pass)", () => {
    // A 64-hex marker that does not match the body must flag; a malformed marker
    // (wrong length) simply is not recognized and the file is treated as N/A.
    const wrong = stamp(BODY).replace(/sha256:[0-9a-f]{64}/, "sha256:" + "0".repeat(64));
    expect(handler(wrong, "dags/team/x/dag.ts")).toHaveLength(1);
  });

  it("handles a marker at EOF with an empty body (hash of empty string)", () => {
    const emptyHash = createHash("sha256").update("", "utf8").digest("hex");
    const content = `// banner\n// @fugue-integrity sha256:${emptyHash}\n`;
    expect(handler(content, "dags/team/x/dag.ts")).toEqual([]);
  });
});
