import { describe, it, expect } from "vitest";
import { createHash } from "node:crypto";
import { handler } from "../../../src/linter/programmatic/fugue-generated-integrity";

const FUGUE_BODY_START = "// @fugue-body-start";
const FUGUE_BODY_END = "// @fugue-body-end";

/** The structural projection — must mirror fugue's authored-codegen exactly. */
function structuralProjection(body: string): string {
  return body.replace(
    new RegExp(`${FUGUE_BODY_START}[\\s\\S]*?${FUGUE_BODY_END}`, "g"),
    FUGUE_BODY_START,
  );
}

/** Build a stamped file exactly as fugue's codegen does: banner + integrity
 *  line (sha256 of the STRUCTURAL PROJECTION of the body) + body. Mirrors
 *  packages/framework's stampGenerated. */
function stamp(body: string): string {
  const hash = createHash("sha256").update(structuralProjection(body), "utf8").digest("hex");
  return (
    "// @generated by `fugue new --from` — regenerate structure from dag.authored.json;\n" +
    "// implement only the @fugue-body regions (structure is integrity-hashed)\n" +
    `// @fugue-integrity sha256:${hash}\n` +
    body
  );
}

const BODY = 'export const dag = defineDag({ nodes: [] });\n';

/** A body with an editable placeholder region, as fetch/transform/source emit. */
const BODY_WITH_PLACEHOLDER =
  "const fetchRecord = defineFetch({\n" +
  '  id: "fetch-record",\n' +
  "  inputSchema: InputSchema,\n" +
  "  outputSchema: FetchRecordSchema,\n" +
  `  ${FUGUE_BODY_START}\n` +
  "  // Placeholder — implement the real fetch\n" +
  "  fetch: async (_input) => ok({ id: \"todo\" }),\n" +
  `  ${FUGUE_BODY_END}\n` +
  "});\n";

describe("fugue-generated-integrity", () => {
  it("passes when the structure matches its stamped hash", () => {
    expect(handler(stamp(BODY), "dags/team/x/dag.ts")).toEqual([]);
  });

  it("flags a STRUCTURAL edit that no longer matches the stamp (hand-rewire)", () => {
    const tampered = stamp(BODY).replace("nodes: []", "nodes: [evil]");
    const violations = handler(tampered, "dags/team/x/dag.ts");
    expect(violations).toHaveLength(1);
    expect(violations[0].rule).toBe("fugue-generated-integrity");
    expect(violations[0].line).toBe(3); // points at the @fugue-integrity marker line
    expect(violations[0].fixHint).toContain("@fugue-body");
  });

  it("PASSES when a placeholder body inside @fugue-body markers is implemented (the contradiction this design resolves)", () => {
    const stamped = stamp(BODY_WITH_PLACEHOLDER);
    // Replace the region's interior with a real implementation — the very edit
    // fugue's nextSteps + README instruct. The structure is unchanged, so the
    // stamp must still verify.
    const implemented = stamped.replace(
      /\/\/ @fugue-body-start[\s\S]*?\/\/ @fugue-body-end/,
      `${FUGUE_BODY_START}\n  fetch: async (i) => ok({ id: await lookup(i) }),\n  ${FUGUE_BODY_END}`,
    );
    expect(handler(implemented, "dags/team/x/dag.ts")).toEqual([]);
  });

  it("FLAGS a structural edit OUTSIDE the @fugue-body markers even when a body region exists", () => {
    const stamped = stamp(BODY_WITH_PLACEHOLDER);
    const rewired = stamped.replace("FetchRecordSchema", "InjectedSchema");
    expect(handler(rewired, "dags/team/x/dag.ts")).toHaveLength(1);
  });

  it("fails CLOSED when non-comment content is prepended above the banner (escapes the hash)", () => {
    const injected = 'import { evil } from "./evil";\n' + stamp(BODY);
    const v = handler(injected, "dags/team/x/dag.ts");
    expect(v).toHaveLength(1);
    expect(v[0].fixHint).toContain("precedes the @fugue-integrity banner");
    // A prepended COMMENT line is harmless and still passes.
    const commented = "// a note\n" + stamp(BODY);
    expect(handler(commented, "dags/team/x/dag.ts")).toEqual([]);
  });

  it("ignores files without the integrity marker (rule N/A)", () => {
    expect(handler("export const x = 1;\n", "src/hand-written.ts")).toEqual([]);
    expect(handler("// @generated but no integrity line\nexport const x = 1;\n", "x.ts")).toEqual([]);
  });

  it("rejects a wrong-but-well-formed hash marker as non-matching (not a silent pass)", () => {
    const wrong = stamp(BODY).replace(/sha256:[0-9a-f]{64}/, "sha256:" + "0".repeat(64));
    expect(handler(wrong, "dags/team/x/dag.ts")).toHaveLength(1);
  });

  it("fails CLOSED on a malformed stamp (corrupted marker) instead of silently N/A", () => {
    // Truncated (63-hex), upper-cased hash, and a trailing space on the marker
    // line all break INTEGRITY_RE but leave the marker PREFIX present — a
    // corrupted stamp, not an absent one, so each must flag rather than pass.
    const base = stamp(BODY);
    const truncated = base.replace(/sha256:[0-9a-f]{64}/, "sha256:" + "a".repeat(63));
    const uppercased = base.replace(/sha256:[0-9a-f]{64}/, "sha256:" + "A".repeat(64));
    const trailingSpace = base.replace(/(sha256:[0-9a-f]{64})/, "$1 ");
    for (const c of [truncated, uppercased, trailingSpace]) {
      const v = handler(c, "dags/team/x/dag.ts");
      expect(v).toHaveLength(1);
      expect(v[0].fixHint).toContain("Malformed");
    }
  });

  // TWO regions with structure between them: the shape that kills the
  // projection mutants a single-region body cannot. Greedy (`[\s\S]*` instead
  // of lazy `*?`) would collapse from the FIRST start to the LAST end,
  // swallowing STRUCTURE_BETWEEN; a dropped `g` flag would collapse only the
  // FIRST region, so implementing the second region's body would break the
  // hash. Both mutants survived the previous suite (every body had one region).
  const TWO_REGION_BODY =
    "const a = defineFetch({\n" +
    `  ${FUGUE_BODY_START}\n  // Placeholder A\n  fetch: async () => ok({}),\n  ${FUGUE_BODY_END}\n` +
    "});\n" +
    "const wiring = connect(a, b); // STRUCTURE BETWEEN the regions\n" +
    "const b = defineTransform({\n" +
    `  ${FUGUE_BODY_START}\n  // Placeholder B\n  transform: async () => ok({}),\n  ${FUGUE_BODY_END}\n` +
    "});\n";

  it("PASSES when the SECOND of two @fugue-body regions is implemented (kills a dropped-g-flag projection mutant)", () => {
    const stamped = stamp(TWO_REGION_BODY);
    const regions = [...stamped.matchAll(/\/\/ @fugue-body-start[\s\S]*?\/\/ @fugue-body-end/g)];
    expect(regions).toHaveLength(2);
    const second = regions[1];
    const implemented =
      stamped.slice(0, second.index) +
      `${FUGUE_BODY_START}\n  transform: async (i) => ok(reshape(i)),\n  ${FUGUE_BODY_END}` +
      stamped.slice(second.index + second[0].length);
    expect(handler(implemented, "dags/team/x/dag.ts")).toEqual([]);
  });

  it("FLAGS a structural edit BETWEEN two @fugue-body regions (kills a lazy→greedy projection mutant)", () => {
    const stamped = stamp(TWO_REGION_BODY);
    const rewired = stamped.replace("connect(a, b)", "connect(a, evil)");
    expect(handler(rewired, "dags/team/x/dag.ts")).toHaveLength(1);
  });

  it("FLAGS an injected @fugue-body-start with NO closing end marker — it cannot hide trailing structure (fail-closed)", () => {
    // An attacker appends a bare start marker and edits/adds structure after
    // it, hoping the projection excludes everything downstream. The lazy regex
    // requires a matching END, so an UNMATCHED start stays literal in the
    // projection: marker + trailing edit both shift the hash → flagged.
    const stamped = stamp(BODY);
    const masked = stamped + `${FUGUE_BODY_START}\nregisterNode(evil);\n`;
    expect(handler(masked, "dags/team/x/dag.ts")).toHaveLength(1);
    // Even the bare unmatched marker alone flags — the projection is not a
    // fixed point over marker injection.
    const markerOnly = stamped + `${FUGUE_BODY_START}\n`;
    expect(handler(markerOnly, "dags/team/x/dag.ts")).toHaveLength(1);
    // An injected start BEFORE an existing region pairs with that region's END
    // and swallows real structure into the collapse — the stamp no longer
    // matches the widened projection, so this too is tamper-EVIDENT.
    const widened = stamp(BODY_WITH_PLACEHOLDER).replace(
      "  inputSchema: InputSchema,",
      `  ${FUGUE_BODY_START}\n  inputSchema: EvilSchema,`,
    );
    expect(handler(widened, "dags/team/x/dag.ts")).toHaveLength(1);
  });

  it("handles a marker at EOF with an empty body (projection of empty string)", () => {
    const emptyHash = createHash("sha256").update("", "utf8").digest("hex");
    const content = `// banner\n// @fugue-integrity sha256:${emptyHash}\n`;
    expect(handler(content, "dags/team/x/dag.ts")).toEqual([]);
  });

  it("the TOPMOST integrity banner governs — an integrity-looking comment INSIDE the body cannot shadow it (round-24 first-match pin)", () => {
    // INTEGRITY_RE is `/m` first-match; correctness relies on the real banner
    // being the topmost `// @fugue-integrity sha256:<64hex>` line. The prelude
    // guard enforces "banner is first" only implicitly, so pin it: a body that
    // legitimately contains such a line (with a DIFFERENT, wrong hash) must still
    // verify against the top banner, and a structural edit must still flag —
    // proving the in-body decoy is treated as hashed CONTENT, never as the stamp.
    const DECOY = "0".repeat(64);
    const bodyWithDecoyBanner =
      "export const dag = defineDag({ nodes: [] });\n" +
      `// note: pinned hash was // @fugue-integrity sha256:${DECOY}\n` +
      "export const meta = { version: 1 };\n";
    // Clean file passes — the top banner's real hash governs; the decoy's wrong
    // hash is inert (it is just projected/hashed structure, not a second stamp).
    expect(handler(stamp(bodyWithDecoyBanner), "dags/team/x/dag.ts")).toEqual([]);
    // A structural edit still flags against the TOP banner — the decoy never
    // shadows it, so "first-match = real banner" holds.
    const tampered = stamp(bodyWithDecoyBanner).replace("nodes: []", "nodes: [evil]");
    expect(handler(tampered, "dags/team/x/dag.ts")).toHaveLength(1);
  });

  // ── Cross-repo golden vector ────────────────────────────────────────────
  // The SAME literal body + digest is pinned in fugue's suite
  // (packages/framework/src/__tests__/cli/authored.test.ts, GOLDEN_MODULE_BODY /
  // GOLDEN_DIGEST). fugue stamps, loom verifies, neither imports the other —
  // so collapse-rule drift between the two structuralProjection copies would
  // otherwise surface only as a false tamper flag at a wave gate. If either
  // side changes the projection or the hash recipe, ITS copy of this test
  // breaks first. Do not update one side without the other.
  const GOLDEN_MODULE_BODY =
    'import { z } from "zod";\n' +
    "\n" +
    "const FetchRecordSchema = z.object({\n" +
    "  id: z.string(),\n" +
    "});\n" +
    "\n" +
    "// fetch-record - Load the record\n" +
    "const fetchRecordNode = fetchNode({\n" +
    '  id: "fetch-record",\n' +
    "  outputSchema: FetchRecordSchema,\n" +
    "  // @fugue-body-start\n" +
    '  fetch: async () => ok({ id: "todo" }),\n' +
    "  // @fugue-body-end\n" +
    "});\n" +
    "\n" +
    "const SummarizeSchema = z.object({\n" +
    "  summary: z.string(),\n" +
    "});\n" +
    "\n" +
    "// summarize - Summarize the record\n" +
    "const summarizeNode = transformNode({\n" +
    '  id: "summarize",\n' +
    "  inputSchema: FetchRecordSchema,\n" +
    "  outputSchema: SummarizeSchema,\n" +
    "  // @fugue-body-start\n" +
    '  transform: (input) => ok({ summary: "todo" }),\n' +
    "  // @fugue-body-end\n" +
    "});\n";

  const GOLDEN_DIGEST = "7ae6384572c018a34302af5fbb2b3f2ce1a8f7fd2f6dbc537fae9c33cfff6054";

  it("reproduces fugue's golden digest for the shared two-region vector (cross-repo collapse-rule parity)", () => {
    expect(
      createHash("sha256").update(structuralProjection(GOLDEN_MODULE_BODY), "utf8").digest("hex"),
    ).toBe(GOLDEN_DIGEST);
  });

  it("PASSES a fugue-stamped artifact built on the golden vector, and flags its structural mutation (drift detector)", () => {
    const stamped =
      "// @generated by `fugue new --from` / `fugue compose` — regenerate structure from dag.authored.json;\n" +
      "// implement only the @fugue-body regions (structure is integrity-hashed)\n" +
      `// @fugue-integrity sha256:${GOLDEN_DIGEST}\n` +
      GOLDEN_MODULE_BODY;
    expect(handler(stamped, "dags/team/golden/dag.ts")).toEqual([]);
    // Implementing a placeholder body still passes (the projection excludes it)…
    const implemented = stamped.replace(
      'fetch: async () => ok({ id: "todo" }),',
      "fetch: async (i) => ok(await lookup(i)),",
    );
    expect(handler(implemented, "dags/team/golden/dag.ts")).toEqual([]);
    // …while a structural mutation between the regions flags.
    const rewired = stamped.replace("inputSchema: FetchRecordSchema,", "inputSchema: EvilSchema,");
    expect(handler(rewired, "dags/team/golden/dag.ts")).toHaveLength(1);
  });
});
