import { describe, it, expect } from "vitest";
import { createHash } from "node:crypto";
import { handler } from "../../../src/linter/programmatic/fugue-generated-integrity";

const FUGUE_BODY_START = "// @fugue-body-start";
const FUGUE_BODY_END = "// @fugue-body-end";

/** The structural projection — must mirror fugue's authored-codegen exactly. */
function structuralProjection(body: string): string {
  return body.replace(
    new RegExp(`${FUGUE_BODY_START}[\\s\\S]*?${FUGUE_BODY_END}`, "g"),
    FUGUE_BODY_START,
  );
}

/** Build a stamped file exactly as fugue's codegen does: banner + integrity
 *  line (sha256 of the STRUCTURAL PROJECTION of the body) + body. Mirrors
 *  packages/framework's stampGenerated. */
function stamp(body: string): string {
  const hash = createHash("sha256").update(structuralProjection(body), "utf8").digest("hex");
  return (
    "// @generated by `fugue new --from` — regenerate structure from dag.authored.json;\n" +
    "// implement only the @fugue-body regions (structure is integrity-hashed)\n" +
    `// @fugue-integrity sha256:${hash}\n` +
    body
  );
}

const BODY = 'export const dag = defineDag({ nodes: [] });\n';

/** A body with an editable placeholder region, as fetch/transform/source emit. */
const BODY_WITH_PLACEHOLDER =
  "const fetchRecord = defineFetch({\n" +
  '  id: "fetch-record",\n' +
  "  inputSchema: InputSchema,\n" +
  "  outputSchema: FetchRecordSchema,\n" +
  `  ${FUGUE_BODY_START}\n` +
  "  // Placeholder — implement the real fetch\n" +
  "  fetch: async (_input) => ok({ id: \"todo\" }),\n" +
  `  ${FUGUE_BODY_END}\n` +
  "});\n";

describe("fugue-generated-integrity", () => {
  it("passes when the structure matches its stamped hash", () => {
    expect(handler(stamp(BODY), "dags/team/x/dag.ts")).toEqual([]);
  });

  it("flags a STRUCTURAL edit that no longer matches the stamp (hand-rewire)", () => {
    const tampered = stamp(BODY).replace("nodes: []", "nodes: [evil]");
    const violations = handler(tampered, "dags/team/x/dag.ts");
    expect(violations).toHaveLength(1);
    expect(violations[0].rule).toBe("fugue-generated-integrity");
    expect(violations[0].line).toBe(3); // points at the @fugue-integrity marker line
    expect(violations[0].fixHint).toContain("@fugue-body");
  });

  it("PASSES when a placeholder body inside @fugue-body markers is implemented (the contradiction this design resolves)", () => {
    const stamped = stamp(BODY_WITH_PLACEHOLDER);
    // Replace the region's interior with a real implementation — the very edit
    // fugue's nextSteps + README instruct. The structure is unchanged, so the
    // stamp must still verify.
    const implemented = stamped.replace(
      /\/\/ @fugue-body-start[\s\S]*?\/\/ @fugue-body-end/,
      `${FUGUE_BODY_START}\n  fetch: async (i) => ok({ id: await lookup(i) }),\n  ${FUGUE_BODY_END}`,
    );
    expect(handler(implemented, "dags/team/x/dag.ts")).toEqual([]);
  });

  it("FLAGS a structural edit OUTSIDE the @fugue-body markers even when a body region exists", () => {
    const stamped = stamp(BODY_WITH_PLACEHOLDER);
    const rewired = stamped.replace("FetchRecordSchema", "InjectedSchema");
    expect(handler(rewired, "dags/team/x/dag.ts")).toHaveLength(1);
  });

  it("fails CLOSED when non-comment content is prepended above the banner (escapes the hash)", () => {
    const injected = 'import { evil } from "./evil";\n' + stamp(BODY);
    const v = handler(injected, "dags/team/x/dag.ts");
    expect(v).toHaveLength(1);
    expect(v[0].fixHint).toContain("precedes the @fugue-integrity banner");
    // A prepended COMMENT line is harmless and still passes.
    const commented = "// a note\n" + stamp(BODY);
    expect(handler(commented, "dags/team/x/dag.ts")).toEqual([]);
  });

  it("ignores files without the integrity marker (rule N/A)", () => {
    expect(handler("export const x = 1;\n", "src/hand-written.ts")).toEqual([]);
    expect(handler("// @generated but no integrity line\nexport const x = 1;\n", "x.ts")).toEqual([]);
  });

  it("rejects a wrong-but-well-formed hash marker as non-matching (not a silent pass)", () => {
    const wrong = stamp(BODY).replace(/sha256:[0-9a-f]{64}/, "sha256:" + "0".repeat(64));
    expect(handler(wrong, "dags/team/x/dag.ts")).toHaveLength(1);
  });

  it("fails CLOSED on a malformed stamp (corrupted marker) instead of silently N/A", () => {
    // Truncated (63-hex), upper-cased hash, and a trailing space on the marker
    // line all break INTEGRITY_RE but leave the marker PREFIX present — a
    // corrupted stamp, not an absent one, so each must flag rather than pass.
    const base = stamp(BODY);
    const truncated = base.replace(/sha256:[0-9a-f]{64}/, "sha256:" + "a".repeat(63));
    const uppercased = base.replace(/sha256:[0-9a-f]{64}/, "sha256:" + "A".repeat(64));
    const trailingSpace = base.replace(/(sha256:[0-9a-f]{64})/, "$1 ");
    for (const c of [truncated, uppercased, trailingSpace]) {
      const v = handler(c, "dags/team/x/dag.ts");
      expect(v).toHaveLength(1);
      expect(v[0].fixHint).toContain("Malformed");
    }
  });

  it("handles a marker at EOF with an empty body (projection of empty string)", () => {
    const emptyHash = createHash("sha256").update("", "utf8").digest("hex");
    const content = `// banner\n// @fugue-integrity sha256:${emptyHash}\n`;
    expect(handler(content, "dags/team/x/dag.ts")).toEqual([]);
  });
});
