/**
 * Programmatic rule: fugue-generated-integrity
 *
 * Files stamped by `fugue new --from` carry a two-line banner over their
 * generated body:
 *
 *     // @generated by `fugue new --from` — DO NOT EDIT; regenerate from dag.authored.json
 *     // @fugue-integrity sha256:<hex>
 *     <generated body…>
 *
 * where `<hex>` is the sha256 of the body (everything after the integrity
 * line). A hand-edit during a loom wave changes the body but not the stamp, so
 * recomputing the hash and comparing makes the edit tamper-EVIDENT: PostToolUse
 * lint surfaces it immediately and the wave-gate full lint blocks on it. This
 * closes the generated-code-hand-edit leak the executable-models bridge left
 * open, WITHOUT a path-based edit gate (which loom's model does not have) — it
 * uses the same detection-at-gate mechanism as every other lint rule.
 *
 * The coupling is one marker-string convention (`@fugue-integrity sha256:`):
 * fugue's codegen stamps it, loom verifies it, neither imports the other. A
 * file without the marker is not a generated file and is ignored (rule N/A).
 *
 * Residual (honest): removing the banner outright disables the check for that
 * file — but fugue's `--from` regeneration restores it (a fixed point) and
 * fugue's gauntlet re-verifies on the next fugue run. The threat this closes is
 * an ACCIDENTAL body edit, not a deliberate banner-strip.
 */

import { createHash } from "node:crypto";
import type { Violation } from "../types";
import { makeViolation } from "../types";

/** The integrity marker; capture group is the declared sha256 of the body. */
const INTEGRITY_RE = /^\/\/ @fugue-integrity sha256:([0-9a-f]{64})$/m;

export function handler(content: string, filePath: string): Violation[] {
  const m = INTEGRITY_RE.exec(content);
  if (m === null) return []; // not a stamped generated file — rule does not apply

  const declared = m[1];
  const markerStart = content.indexOf(m[0]);
  const nl = content.indexOf("\n", markerStart + m[0].length);
  // Body = everything after the marker line's terminating newline. A marker at
  // EOF (no body) hashes the empty string, matching a codegen that stamped an
  // empty file.
  const body = nl === -1 ? "" : content.slice(nl + 1);
  const actual = createHash("sha256").update(body, "utf8").digest("hex");
  if (actual === declared) return [];

  const line = content.slice(0, markerStart).split("\n").length;
  return [
    makeViolation(
      "fugue-generated-integrity",
      filePath,
      line,
      m[0],
      "Generated file body no longer matches its @fugue-integrity hash — `fugue new --from` owns this file; do not hand-edit. Change the AuthoredDag sidecar and regenerate.",
    ),
  ];
}
