/**
 * Programmatic rule: fugue-generated-integrity
 *
 * Files stamped by `fugue new --from` carry a three-line banner over their
 * generated body:
 *
 *     // @generated by `fugue new --from` — regenerate structure from dag.authored.json;
 *     // implement only the @fugue-body regions (structure is integrity-hashed)
 *     // @fugue-integrity sha256:<hex>
 *     <generated body…>
 *
 * where `<hex>` is the sha256 of the STRUCTURAL PROJECTION of the body
 * (everything after the integrity line, with each `@fugue-body-start …
 * @fugue-body-end` region collapsed to a single marker). The projection is why
 * the rule does not contradict fugue's own scaffold: the machine-owned
 * STRUCTURE (imports, schemas, node ids, wiring, registration) is hashed, but
 * the placeholder node bodies the scaffold instructs you to implement live
 * inside `@fugue-body` regions and are EXCLUDED — implementing them is expected
 * and leaves the hash intact. A hand-edit to the STRUCTURE changes the
 * projection but not the stamp, so recomputing the hash and comparing makes
 * that edit tamper-EVIDENT.
 *
 * Detection is at the LINT GATE: this is a programmatic rule, so it runs in the
 * full/wave-gate tier (programmatic rules do NOT run in the immediate/PostToolUse
 * tier — that tier is regex-only). The tamper-evidence window is therefore a
 * wave, not a single tool call. This closes the generated-code-hand-edit leak
 * the executable-models bridge left open WITHOUT a path-based edit gate (which
 * loom's model does not have) — it uses the same detection-at-gate mechanism as
 * every other lint rule.
 *
 * The coupling is the marker convention (`@fugue-integrity sha256:` + the two
 * `@fugue-body` strings + the collapse rule): fugue's codegen stamps it, loom
 * verifies it, neither imports the other. A file without the integrity marker is
 * not a generated file and is ignored (rule N/A).
 *
 * Residual (honest): this targets an ACCIDENTAL structural edit. Two deliberate
 * circumventions are out of scope and equivalent to each other — removing the
 * banner outright, or wrapping hand-edited structure in fake `@fugue-body`
 * markers to hide it from the projection. Both are restored by `fugue new
 * --from --force` regeneration (a fixed point that overwrites the edit).
 */

import { createHash } from "node:crypto";
import type { Violation } from "../types";
import { makeViolation } from "../types";

/** The integrity marker; capture group is the declared sha256 of the projection. */
const INTEGRITY_RE = /^\/\/ @fugue-integrity sha256:([0-9a-f]{64})$/m;

/** Loose presence probe: the marker prefix appears at all, even malformed. A
 *  file carrying this but failing the strict INTEGRITY_RE has a CORRUPTED stamp
 *  (truncated/upper-case hash, trailing whitespace, CRLF) — that is a structural
 *  change to the banner, so it must fail CLOSED rather than fall through to the
 *  no-marker "not a generated file" N/A path (which would silently disable the
 *  check — the accidental-edit class this rule targets).
 *
 *  LINE-ANCHORED, like the strict form. A real banner always begins its own
 *  line; a marker quoted mid-line — inside a JSDoc block explaining the format,
 *  as this very file does — is documentation, not a corrupted stamp. An
 *  unanchored probe reported the rule's own doc comment as a malformed banner. */
const INTEGRITY_MARKER_PREFIX_RE = /^\/\/ @fugue-integrity sha256:/m;
const INTEGRITY_MARKER_PREFIX = "// @fugue-integrity sha256:";

/** Marker strings delimiting a human-owned placeholder body. Must match
 *  fugue's authored-codegen `FUGUE_BODY_START` / `FUGUE_BODY_END` exactly. */
const FUGUE_BODY_START = "// @fugue-body-start";
const FUGUE_BODY_END = "// @fugue-body-end";

/** Collapse each `@fugue-body` region (markers + interior) to a single marker,
 *  identically to fugue's `structuralProjection`, so the hash covers only the
 *  machine-owned structure. Region count and order stay in the hash; contents
 *  are free to implement. */
const structuralProjection = (body: string): string =>
  body.replace(
    new RegExp(`${FUGUE_BODY_START}[\\s\\S]*?${FUGUE_BODY_END}`, "g"),
    FUGUE_BODY_START,
  );

export function handler(content: string, filePath: string): Violation[] {
  const m = INTEGRITY_RE.exec(content);
  if (m === null) {
    // No well-formed marker. If the marker PREFIX is present the stamp is
    // corrupted (not absent) — fail closed instead of silently N/A.
    const probe = INTEGRITY_MARKER_PREFIX_RE.exec(content);
    if (probe === null) return []; // genuinely not a stamped generated file — rule N/A
    const idx = probe.index;
    return [
      makeViolation(
        "fugue-generated-integrity",
        filePath,
        content.slice(0, idx).split("\n").length,
        content.slice(idx).split("\n", 1)[0] ?? INTEGRITY_MARKER_PREFIX,
        "Malformed @fugue-integrity stamp (hash must be exactly 64 lowercase hex chars on its own `// @fugue-integrity sha256:<hex>` line) — the banner has been altered; regenerate with `fugue new --from`.",
      ),
    ];
  }

  const declared = m[1];
  const markerStart = content.indexOf(m[0]);

  // Anchor: the hash covers only what follows the integrity line, so anything
  // PREPENDED above the banner (an injected import, a directive) escapes it.
  // The generated banner is comment lines only, so require every line before
  // the marker to be blank or a `//` comment — real code above the banner fails
  // closed rather than riding along unhashed.
  const preludeLines = content.slice(0, markerStart).split("\n").slice(0, -1);
  if (preludeLines.some((l) => l.trim() !== "" && !l.trimStart().startsWith("//"))) {
    return [
      makeViolation(
        "fugue-generated-integrity",
        filePath,
        1,
        preludeLines.find((l) => l.trim() !== "" && !l.trimStart().startsWith("//")) ?? "",
        "Non-comment content precedes the @fugue-integrity banner — the generated banner must be at the top of the file; content prepended above it escapes the integrity hash. Move it below the generated structure or regenerate.",
      ),
    ];
  }
  const nl = content.indexOf("\n", markerStart + m[0].length);
  // Body = everything after the marker line's terminating newline. A marker at
  // EOF (no body) projects the empty string, matching a codegen that stamped an
  // empty file.
  const body = nl === -1 ? "" : content.slice(nl + 1);
  const actual = createHash("sha256").update(structuralProjection(body), "utf8").digest("hex");
  if (actual === declared) return [];

  const line = content.slice(0, markerStart).split("\n").length;
  return [
    makeViolation(
      "fugue-generated-integrity",
      filePath,
      line,
      m[0],
      "Generated file STRUCTURE no longer matches its @fugue-integrity hash — `fugue new --from` owns the structure; implement node bodies inside the @fugue-body markers (excluded from the hash), and change the AuthoredDag sidecar + regenerate for structural changes.",
    ),
  ];
}
