/**
 * Orchestration shared kernel — facade. The kernel is split into pure
 * sub-domain volumes (identity, bytes, artifacts, roster, publication,
 * completion, diagnostics, actions, effects); this module re-exports the
 * full public surface so every existing import site is unchanged.
 * Pure module: no I/O, no clock, no randomness.
 */

export { MAX_DIAGNOSTIC_MESSAGE_LENGTH, canonicalRecord, canonicalStructuralEquals, parseArtifactByteLength, parseArtifactDigest, parseContextDigest, parseEffectId, parseOrchestrationRunId, parseRequestId, parseSlotId, type ArtifactByteLength, type ArtifactByteLengthError, type ArtifactDigest, type AuthorityIdentityKind, type ContextDigest, type DomainResult, type EffectId, type IdentityParseError, type NonEmpty, type OrchestrationRunId, type RequestId, type SemanticAttempt, type SlotId } from './identity';
export { MAX_DENSE_DATA_ARRAY_LENGTH, MAX_SEMANTIC_PAYLOAD_ARRAY_LENGTH, digestRawTranscriptBytes, type DataBoundaryReason, type RawTranscriptBytesError } from './bytes';
export { AGENT_REQUIRED_SKILLS, ORCHESTRATION_PROGRAMS, parseFixedArtifactSlot, type ExactHarnessBinding, type FixedArtifactSlot, type FixedArtifactSlotError, type OrchestrationProgram } from './artifacts';
export { parseAgentRequestAuthority, parseStoredAgentRequestAuthority, parseAgentRequestAuthorityForAttempt, parseAgentRosterSlot, parseArtifactRef, parseExactRoster, type AgentRequestAuthority, type AgentRequestAuthorityError, type AgentRequestAuthorityViolation, type AgentRosterSlot, type AgentRosterSlotError, type ArtifactRef, type ArtifactRefError, type ExactRoster, type ExactRosterError, type RosterViolation, type UnissuedResultCause } from './roster';
export { MAX_PUBLICATION_REGISTRATION_BYTES, createAtomicInitialPublicationClaimPort, createInitialBatchPublicationReconciler, createInitialPublicationEffectPort, createPublicationAuthorityResolver, parseBatchPublishedReceipt, parseIssuedSpawnRequest, prepareInitialBatchPublicationIntent, reduceInitialPublicationClaim, type AcceptedInitialPublicationClaim, type AtomicInitialPublicationClaim, type AtomicInitialPublicationClaimPort, type BatchPublicationIdentity, type BatchPublicationRegistrationLookup, type BatchPublishedReceipt, type ContextReference, type InitialBatchPublicationIntent, type InitialBatchPublicationReconciler, type InitialPublicationClaimError, type InitialPublicationClaimKey, type InitialPublicationClaimOutcome, type InitialPublicationClaimRequest, type InitialPublicationEffectError, type InitialPublicationEffectExecutor, type InitialPublicationEffectPort, type InitialPublicationIssuanceAuthority, type InitialSpawnRequestInput, type IssuedSpawnRequestProof, type PublicationAuthorityResolutionError, type PublicationAuthorityResolver, type PublishedSpawnRequestAuthority, type RegisteredBatchPublicationAuthority, type SpawnRequest, type TrustedPublicationRegistrationLoader } from './publication';
export { acceptedAgentResult, parseCompleteRoster, type AcceptedAgentResult, type AcceptedAgentResultError, type CompleteRoster, type CompleteRosterError, type SemanticPayloadDiagnostic, type SemanticPayloadFailureReason, type SemanticPayloadParseError, type SemanticPayloadParser } from './completion';
export { infrastructureRetryDiagnostic, parseSemanticAttemptPairAuthority, semanticRetryDiagnostic, terminalBlockedDiagnostic, type BlockedDiagnostic, type DiagnosticConstructionError, type InfrastructureRetryDiagnostic, type InfrastructureRetryDiagnosticInput, type SemanticAttemptPairAuthority, type SemanticRetryDiagnostic, type SemanticRetryDiagnosticInput, type TerminalBlockedDiagnostic, type TerminalBlockedDiagnosticInput, type UserDecisionRequest } from './diagnostics';
export { awaitUserAction, blockedAction, doneAction, issueInitialSpawnRequests, parseBlockedDiagnostic, rehydrateIssuedSpawnRequests, spawnBatchAction, type AwaitUserAction, type BlockedAction, type DoneAction, type ExternalAction, type ExternalActionError, type SpawnBatchAction } from './actions';
export { parseVerifiedIndexInstalled, reconcileEffectReceipt, type AgentRequestsReserved, type ArtifactSetPublished, type ArtifactSlotAssignment, type ArtifactSlotConflict, type CaptureRawTranscript, type CommitProtectedWaveState, type EffectIntent, type EffectReceipt, type EffectReceiptError, type GitRemediationInspected, type InspectGitRemediation, type InstallVerifiedIndex, type ProtectedWaveStateCommitted, type PublishArtifactSet, type RawTranscriptCaptured, type ReserveAgentRequests, type VerifiedIndexInstalled } from './effects';
